version: '3.3'
services:
  db:
    image: mysql:5.7.37
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'P@ssw0rd'
      MYSQL_ROOT_PASSWORD: 'p@ssw0rd'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data:/var/lib/mysql
      - ./scripts:/var/develop/scripts
      - ./out:/var/develop/out
      - ./log/mysql:/var/log/mysql
