version: '3.3'
services:
  db:
    image: mariadb:10.6.7
    restart: always
    environment:
      MARIADB_DATABASE: 'db'
      MARIADB_USER: 'user'
      MARIADB_PASSWORD: 'P@ssw0rd'
      MARIADB_ROOT_PASSWORD: 'p@ssw0rd'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data:/var/lib/mysql
      - ./scripts:/var/develop/scripts
      - ./out:/var/develop/out
      - ./log/mysql:/var/log/mysql
