version: "3.9"
services:
  otel:
    image: amazon/aws-otel-collector:latest
    command: --config /config/collector-config-local.yml
    volumes:
      - .:/config
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION=us-east-1
    ports:
      - '4317:4317'

  productservice:
    build: ProductService/
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION=us-east-1
      - MYSQLCONNSTR_PRODUCTSERVICE
      - INSTANCE_ID
      - OTEL_RESOURCE_ATTRIBUTES=service.name=product-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4317
    ports:
      - "80:80"
      - "443:443"
